services:
  - type: web
    name: django-backend
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: daphne backend.asgi:application --port $PORT --bind 0.0.0.0 -v2
    envVars:
      - key: PGDATABASE
        value: neondb
      - key: PGUSER
        value: neondb_owner
      - key: PGPASSWORD
        value: d4VpECP0JuOS
      - key: PGHOST
        value: ep-lucky-glade-a1crcutq.ap-southeast-1.aws.neon.tech
      - key: PGPORT
        value: '5432'
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'True'
      - key: ALLOWED_HOSTS
        value: '127.0.0.1,localhost'
  - type: web
    name: react-frontend
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: serve -s frontend/build
    envVars:
      - key: NODE_ENV
        value: production
