# Generated by Django 5.0.6 on 2024-09-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamescore_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
